### ISSUE TITLE
Wrong available Heating Modes

### ISSUE THREAD

**Issue by mike4001** [signalkraft/mypyllant-component#113]
### Before submitting a new issue

- [x] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [ ] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

Home Assistant shows available heating modes as "Auto", "Heating/Cooling", "Off"

But correct would be "Auto", "Day", "Night", "Off"

![image](https://github.com/signalkraft/mypyllant-component/assets/26521177/e632d7dd-ebf7-40fd-b6fa-d636a4a0645a)

![image](https://github.com/signalkraft/mypyllant-component/assets/26521177/36ac6721-66e0-4e25-bf86-b2aa7625ed1d)

### Logs

```
Put your debug logs here
Be careful not to include tokens, emails, and other personal information
```

**Comment by mike4001** [comment]
One addition

It seems that when I switch to "Heizen/Kühlen" in Home Assistant this is "Day" mode in the app.

**Comment by signalkraft** [comment]
Home Assistant has a fixed set of modes and presets, and day / night mode don't exist there. Based on your screenshot, I tried a new mapping in https://github.com/signalkraft/mypyllant-component/releases/tag/v0.7.4b1

Now mode should switch between on (auto) and off, and preset should switch between none (in off or auto mode), comfort (day) or eco (night).

If you can think of a cleaner mapping, I'm open to suggestions. Modes & presets are documented here: https://developers.home-assistant.io/docs/core/entity/climate/#hvac-modes

**Comment by fodorg01** [comment]
@signalkraft Thank you for this improvement. This really seems to be a cleaner mapping.

I am also trying now to switch to this integration due to the Vaillant API migration. My use case is that I don't use Vaillant's "Auto" or "Off" mode; my automations set either "Day" or "Night", as well as they also set the associated temperature. For my automations I implemented 2 kinds of scripts before:

- Set mode (day / night) and set associated temperature,
- Set the temperature of the active mode, without changing the mode.

So in these days I am trying to make this work with your integration. Yesterday evening I figured out how to set the mode (day / night), by using the service call (`mypyllant.set_zone_operating_mode`) with the parameters `DAY` or `SET_BACK`, as it was mentioned here: https://github.com/signalkraft/mypyllant-component/issues/104#issuecomment-1956545129

My questions:

1. Do I understand correctly that this way of setting the day/night mode is not changed by your new mapping in [v0.7.4b1](https://github.com/signalkraft/mypyllant-component/releases/tag/v0.7.4b1)?
2. How is it possible to set the temperature associated with the Day / Night mode? (It is possible in the app as shown on the attached screenshot.) Or, alternatively, to set the temperature of the currently active mode? If I try `climate.set_temperature` on the climate entity, it doesn't do this change.

![Screenshot_20240222_063328](https://github.com/signalkraft/mypyllant-component/assets/145673205/59f9aa5e-f08c-4af9-89f7-a76028c4d4fa)

**Comment by mike4001** [comment]
> Home Assistant has a fixed set of modes and presets, and day / night mode don't exist there. Based on your screenshot, I tried a new mapping in https://github.com/signalkraft/mypyllant-component/releases/tag/v0.7.4b1
> 
> Now mode should switch between on (auto) and off, and preset should switch between none (in off or auto mode), comfort (day) or eco (night).
> 
> If you can think of a cleaner mapping, I'm open to suggestions. Modes & presets are documented here: https://developers.home-assistant.io/docs/core/entity/climate/#hvac-modes

Thank you. Basically it works. Only problem with this solution is that we now have 2 "none" presets which always show both in the Presets list ... and you do not know which is for Off and which is for Auto

![image](https://github.com/signalkraft/mypyllant-component/assets/26521177/a2defd2a-457c-4cb5-bbd3-627d486ff992)

If you match the available Presets maybe this would fit better? There would also be no double Presets

HVACMode.OFF, No Preset -> Off Mode
HVACMode.AUTO, COMFORT Preset -> Auto Mode
HVACAction.HEATING, HOME Preset -> Day Mode
HVACAction.HEATING, SLEEP Preset -> Night Mode

**Comment by signalkraft** [comment]
https://github.com/signalkraft/myPyllant/releases/tag/v0.7.4b2 should remove the duplicate "none" preset.

> HVACMode.OFF, No Preset -> Off Mode
> HVACMode.AUTO, COMFORT Preset -> Auto Mode
> HVACMode.HEAT, HOME Preset -> Day Mode
> HVACMode.HEAT, SLEEP Preset -> Night Mode

The problem with mixing presets and modes is that changing one will affect the other. What if you're in day preset, but change from heat to auto mode? Should it go to comfort preset? Or stay in home? Etc.

With modes only being off & auto, and presets being none / comfort / home, there should only be one mapping from Vaillant's modes to HA's modes and presets:

HVACMode.OFF, No Preset -> Off Mode
HVACMode.AUTO, No Preset -> Auto Mode
HVACMode.AUTO, Home Preset -> Day Mode
HVACMode.AUTO, Eco Preset -> Night Mode

Switching from auto mode to off will set the preset to none, but that seems fair. Other than that, there should be no "interference" between modes and presets now.

**Comment by signalkraft** [comment]
@fodorg01 I couldn't tell you, I don't have a VRC700 system. Just browse the services and try them on your setup. There are services for setback temperature and manual mode temperature, my guess is that these might work for you.

**Comment by mike4001** [comment]
Thanks again for your quick update, hope I don't bother you too much :-)

One problem remains:

If I am in Day-Mode and I want to switch to Auto-Mode I would have to select the "None" Preset, But this does not move me to Auto-Mode with None-Preset, but instead to Off-Mode with None-preset.
Once in Off-Mode with None-Preset I can then switch back to Auto mode (with None-preset staying in place)

But I do not know if this is fixable because both modes have a "None-Preset" at the moment.

**Comment by boelle** [comment]
not sure if this is related

![image](https://github.com/signalkraft/mypyllant-component/assets/3832239/ca50dd73-1060-412f-aa3d-630ab583f7ac)

if i pick anything other than Cylinder Boost i get an error

Manual gives this one:

![image](https://github.com/signalkraft/mypyllant-component/assets/3832239/a5993bb0-d525-402d-897d-4ad8a822dc7d)

Day gives this:

![image](https://github.com/signalkraft/mypyllant-component/assets/3832239/d36f5631-d79b-4756-ba80-ca8321a32b13)

Auto:

![image](https://github.com/signalkraft/mypyllant-component/assets/3832239/672f62ad-78f8-4bf2-8d81-96f63ea63cad)

The myvaillant app on the phone gives me auto and day along with off as options

![image](https://github.com/signalkraft/mypyllant-component/assets/3832239/ea2ef11d-6aee-4171-8f52-327a1f5c5bea)

if i pick day as option and return to HA i can see the day option selected

![image](https://github.com/signalkraft/mypyllant-component/assets/3832239/8b69be38-80c0-4f2d-821c-8a598d3d027a)

i can then select either off or cylinder boost, but still not day

same deal with auto

![image](https://github.com/signalkraft/mypyllant-component/assets/3832239/25949507-8439-4b50-a398-ba1401385225)


maybe i screwed up?

**Comment by mike4001** [comment]
@boelle 

Are you on the latest Beta Release?

The inability to change the Modes for Hot water were fixed in [v0.7.4b0](https://github.com/signalkraft/mypyllant-component/releases/tag/v0.7.4b0)

**Comment by boelle** [comment]
> @boelle
> 
> Are you on the latest Beta Release?
> 
> The inability to change the Modes for Hot water were fixed in [v0.7.4b0](https://github.com/signalkraft/mypyllant-component/releases/tag/v0.7.4b0)

nope... will try now

**Comment by boelle** [comment]
that worked

**Comment by boelle** [comment]
btw... what does cylinder boost mean?

i assume that auto follow a schedule i can set either via the app or via the integration
and likewise Day will just stick on the target temp for day time

but then what about manual mode?

**Comment by mike4001** [comment]
> btw... what does cylinder boost mean?
> 
> i assume that auto follow a schedule i can set either via the app or via the integration and likewise Day will just stick on the target temp for day time
> 
> but then what about manual mode?

Cylinder Boost should be "Warm water Boost" which is also in the App. But I don't know what it does exactly.

Manual Mode does not exist and should be removed ... see here: https://github.com/signalkraft/mypyllant-component/issues/109#issuecomment-1956016173

**Comment by fodorg01** [comment]
As this discussion is about heating modes, wouldn't [this ](https://github.com/signalkraft/mypyllant-component/issues/109)be a better place for the warm water mode discussions?

**Comment by boelle** [comment]
@fodorg01 you are correct
also i need to check my GW model

**Comment by mike4001** [comment]
It´s on the main page. under the 3 vertical dots

But @fodorg01 is correct. This topic is actually about heating and not water heating :-)

Let´s use #109 from now on.

**Comment by signalkraft** [comment]
@mike4001 in https://github.com/signalkraft/mypyllant-component/releases/tag/v0.7.4b3 selecting none preset should return the system to auto mode. Let me know if that works!

**Comment by mike4001** [comment]
> @mike4001 in https://github.com/signalkraft/mypyllant-component/releases/tag/v0.7.4b3 selecting none preset should return the system to auto mode. Let me know if that works!

Looks good, thanks again :-)

I can now switch around and everything seems consitent.
