### ISSUE TITLE
Requirements for mypyllant not found: ['myPyllant==0.9.0']

### ISSUE THREAD

**Issue by FrankCAD** [signalkraft/mypyllant-component#286]
### Before submitting a new issue

- [x] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [x] I've checked [known issues](https://signalkraft.com/mypyllant-component/#known-issues)
- [ ] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

- Running on Synology docker Container Manager (included docker container logfile _HomeAssistant-latest.csv_)
- Version 2025.1.3 of HA installed
- Version 2.0.3 of HACS installed
- Version 0.9.1 of mypyllant installed

Adding the myVAILLANT integration results with the error message _Config-flow kon niet geladen worden: 500 Internal Server Error Server got itself in trouble_

### Logs

Log from Synology Container Manager: [HomeAssistant-latest.csv](https://github.com/user-attachments/files/18538436/HomeAssistant-latest.csv)

Log from Home Assistant Core:
```
Logger: aiohttp.server
Bron: /usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py:451
Eerst voorgekomen: 15:53:07 (2 gebeurtenissen)
Laatst gelogd: 16:29:48
Error handling request

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 172, in post
    return await self._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 179, in _post_impl
    return await super()._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1315, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1340, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1536, in async_create_flow
    handler = await _async_get_flow_handler(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.hass, handler_key, self._hass_config
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3333, in _async_get_flow_handler
    await _load_integration(hass, domain, hass_config)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3310, in _load_integration
    await async_process_deps_reqs(hass, hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 575, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
        hass, integration.domain
    )
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 54, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 170, in async_get_integration_with_requirements
    await future
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 159, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 182, in _async_process_integration
    await self.async_process_requirements(
        integration.domain, integration.requirements
    )
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 264, in async_process_requirements
    self._raise_for_failed_requirements(name, missing)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 292, in _raise_for_failed_requirements
    raise RequirementsNotFound(integration, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for mypyllant not found: ['myPyllant==0.9.0'].
```

**Comment by sto-code** [comment]
I got the same issue on Hass.io after updating HA Core to 2025.2.1

**Comment by KlausGause** [comment]
> I got the same issue on Hass.io after updating HA Core to 2025.2.1

After updating to 2025.2.2 the problem was solved.

**Comment by FrankCAD** [comment]
Can anyone help me to solve this problem.

The key problem seems to be the very general error message `500 Internal Server Error Server got itself in trouble`.
In the HA log i found this line:
`Unable to install package myPyllant==0.9.0: error: failed to create directory '/.cache/uv': Permission denied (os error 13)`,
which seems to fit the general error message.

updated to:
- Version 2025.2.5 of HA installed
- Version 2.0.5 of HACS installed

**Comment by FrankCAD** [comment]
@boelle 

just updated to:
- Version 2025.5.1 of HA
- Version 2.0.5 of HACS

Trying to add the myVaillant integration (v0.9.1) i get the error message 

> Deze integratie ondersteunt geen configuratie via de UI. Als je deze link hebt gevolgd vanaf de Home Assistant-website, zorg er dan voor dat je de nieuwste versie van Home Assistant gebruikt.

this translates to 

> This integration does not support configuration through the UI. If you followed this link from the Home Assistant website, make sure you are using the latest version of Home Assistant.

So it is still an issue, although the symptoms are different.
Log from Home Assistant Core:

> 2025-05-13 11:52:11.854 WARNING (MainThread) [async_upnp_client.profiles.dlna] Only InstanceID 0 is supported

**Comment by boelle** [comment]
@signalkraft poke

**Comment by FrankCAD** [comment]
> [@signalkraft](https://github.com/signalkraft) poke

I have migrated to Home Assistant Green and abandoned Home Assistant on the Synology. 
I don not experience any significant issues on the Green. So as far as i am concerned this issue can be closed.
